# report_generator.py
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas
from reportlab.platypus import Table, TableStyle, Paragraph, SimpleDocTemplate, Spacer
from reportlab.lib.styles import getSampleStyleSheet
import io
from datetime import datetime

styles = getSampleStyleSheet()

def build_comparison_pdf_bytes(meta: dict, summary: dict, compare: dict):
    """
    meta: {"report_title": str, "generated_by": str}
    summary: summary object returned by /summarize
    compare: object returned by /compare_offers (includes offer_a, offer_b, best_offer)
    Returns: bytes of PDF
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, leftMargin=20*mm, rightMargin=20*mm, topMargin=20*mm, bottomMargin=20*mm)
    story = []

    # Header
    title = meta.get("report_title", "Car Contract — Comparison Report")
    gen_by = meta.get("generated_by", "Car Contract AI")
    ts = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    story.append(Paragraph(f"<b>{title}</b>", styles["Title"]))
    story.append(Paragraph(f"<i>Generated by {gen_by} — {ts}</i>", styles["Normal"]))
    story.append(Spacer(1, 8))

    # Plain summary
    story.append(Paragraph("<b>Contract Plain Summary</b>", styles["Heading2"]))
    story.append(Paragraph(summary.get("plain_summary", "No summary available."), styles["BodyText"]))
    story.append(Spacer(1, 8))

    # Key numbers table from summary.key_numbers (if present)
    key_numbers = summary.get("key_numbers", {})
    if key_numbers:
        story.append(Paragraph("<b>Key Numbers</b>", styles["Heading3"]))
        data = [["Field", "Value"]]
        for k, v in key_numbers.items():
            data.append([k, v or "N/A"])
        t = Table(data, colWidths=[80*mm, 80*mm])
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f2f2f2")),
            ("GRID", (0,0), (-1,-1), 0.25, colors.grey),
            ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
            ("VALIGN", (0,0), (-1,-1), "MIDDLE"),
        ]))
        story.append(t)
        story.append(Spacer(1,8))

    # Red flags
    story.append(Paragraph("<b>Red Flags</b>", styles["Heading3"]))
    rf = summary.get("red_flags", [])
    if rf:
        for r in rf:
            story.append(Paragraph(f"• {r}", styles["BodyText"]))
    else:
        story.append(Paragraph("No major red flags detected.", styles["BodyText"]))
    story.append(Spacer(1,8))

    # Fairness scores
    story.append(Paragraph("<b>Fairness Scores</b>", styles["Heading3"]))
    a = compare.get("offer_a", {})
    b = compare.get("offer_b", {})
    data = [
        ["Metric", "Offer A", "Offer B"]
    ]
    # Common fields we try to show
    def safeget(o, k): 
        return o.get("fields", {}).get(k) or o.get("fields", {}).get(k.lower()) or "N/A"
    fields = ["APR", "Tenure_Months", "Monthly_Payment", "Buyout_Price"]
    for f in fields:
        data.append([f, safeget(a, f), safeget(b, f)])
    data.append(["Fairness Score", str(a.get("score","N/A")), str(b.get("score","N/A"))])
    data.append(["Best Offer", "A" if compare.get("best_offer")=="A" else "", "B" if compare.get("best_offer")=="B" else ""])
    t2 = Table(data, colWidths=[60*mm, 60*mm, 60*mm])
    t2.setStyle(TableStyle([
        ("GRID", (0,0), (-1,-1), 0.25, colors.grey),
        ("BACKGROUND", (0,0), (-1,0), colors.HexColor("#f2f2f2")),
        ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
    ]))
    story.append(t2)
    story.append(Spacer(1,8))

    # Why score reduced (reasons)
    story.append(Paragraph("<b>Why scores changed</b>", styles["Heading3"]))
    story.append(Paragraph("Offer A:", styles["BodyText"]))
    for r in a.get("reasons", []):
        story.append(Paragraph(f"• {r}", styles["BodyText"]))
    story.append(Paragraph("Offer B:", styles["BodyText"]))
    for r in b.get("reasons", []):
        story.append(Paragraph(f"• {r}", styles["BodyText"]))
    story.append(Spacer(1,8))

    # Negotiation tips
    story.append(Paragraph("<b>Negotiation Messages (AI)</b>", styles["Heading3"]))
    nm = compare.get("offer_a", {}).get("fields", {})
    # negotiation messages from compare_resp top-level (we expect negotiation_tips present at result-level)
    top_neg = compare.get("negotiation_tips") or {}
    # if top_neg is not present, try summary-level negotiation (fallback)
    if top_neg:
        story.append(Paragraph("<i>Polite</i>:", styles["BodyText"]))
        story.append(Paragraph(top_neg.get("polite",""), styles["BodyText"]))
        story.append(Paragraph("<i>Firm</i>:", styles["BodyText"]))
        story.append(Paragraph(top_neg.get("firm",""), styles["BodyText"]))
        story.append(Paragraph("<i>Legal-Based</i>:", styles["BodyText"]))
        story.append(Paragraph(top_neg.get("legal_based",""), styles["BodyText"]))
    else:
        story.append(Paragraph("No negotiation messages provided.", styles["BodyText"]))

    # Footer / signature
    story.append(Spacer(1,12))
    story.append(Paragraph("Generated by Car Contract AI", styles["Normal"]))
    story.append(Paragraph(f"Report generated on {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}", styles["Normal"]))

    doc.build(story)

    buffer.seek(0)
    pdf_bytes = buffer.read()
    buffer.close()
    return pdf_bytes
