# backend/premium_report.py
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Flowable, PageBreak
)
from reportlab.lib.units import inch
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
import io
import datetime
import json

# Use built-in fonts to avoid missing font errors
# (ReportLab builtin fonts like Helvetica will be used directly in styles)

styles = getSampleStyleSheet()
TITLE_STYLE = ParagraphStyle(
    "TitleStyle",
    parent=styles["Title"],
    alignment=TA_CENTER,
    fontName="Helvetica-Bold",
    fontSize=18,
    spaceAfter=6
)
HEADING_STYLE = ParagraphStyle(
    "HeadingStyle",
    parent=styles["Heading2"],
    alignment=TA_LEFT,
    fontName="Helvetica-Bold",
    fontSize=12,
    spaceBefore=8,
    spaceAfter=4
)
NORMAL = ParagraphStyle(
    "Normal",
    parent=styles["BodyText"],
    fontName="Helvetica",
    fontSize=10,
    leading=12
)
SMALL = ParagraphStyle(
    "Small",
    parent=styles["BodyText"],
    fontName="Helvetica",
    fontSize=8,
    leading=10
)
CODE = ParagraphStyle(
    "Code",
    parent=styles["Code"],
    fontName="Helvetica",
    fontSize=9,
    leading=12
)

class ScoreBar(Flowable):
    """
    A simple horizontal score bar (colored) with the numeric score displayed.
    """
    def __init__(self, score, width=5.5*inch, height=0.28*inch):
        Flowable.__init__(self)
        self.score = max(0, min(100, int(score) if score is not None else 0))
        self.width = width
        self.height = height

    def draw(self):
        # background
        self.canv.setStrokeColor(colors.grey)
        self.canv.setFillColor(colors.whitesmoke)
        self.canv.rect(0, 0, self.width, self.height, fill=1, stroke=0)

        # colored portion based on score
        w = (self.score / 100.0) * self.width
        # color scale: green -> yellow -> red
        if self.score >= 80:
            fill = colors.HexColor("#2ECC71")  # green
        elif self.score >= 60:
            fill = colors.HexColor("#F1C40F")  # yellow
        else:
            fill = colors.HexColor("#E74C3C")  # red

        self.canv.setFillColor(fill)
        self.canv.rect(0, 0, w, self.height, fill=1, stroke=0)

        # score text
        self.canv.setFillColor(colors.black)
        self.canv.setFont("Helvetica-Bold", 10)
        self.canv.drawCentredString(self.width/2, self.height/2 - 4, f"Fairness Score: {self.score}/100")


def _safe_to_text(v):
    if v is None:
        return "—"
    if isinstance(v, (dict, list)):
        try:
            return json.dumps(v, ensure_ascii=False)
        except:
            return str(v)
    return str(v)


def build_comparison_pdf_bytes(meta: dict, summary: dict, compare: dict) -> bytes:
    """
    Builds the premium comparison PDF and returns bytes.
    meta: dict with keys like report_title, generated_by
    summary: dict (from /summarize) — expects plain_summary, red_flags (list), key_numbers (dict), confidence
    compare: dict returned by /compare_offers — offer_a, offer_b, best_offer, negotiation_tips (optional)
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter,
                            leftMargin=0.6*inch, rightMargin=0.6*inch,
                            topMargin=0.5*inch, bottomMargin=0.6*inch)

    elements = []

    # Header
    title = meta.get("report_title", "Contract Comparison Report")
    elements.append(Paragraph(title, TITLE_STYLE))
    subtitle_text = meta.get("generated_by", f"Generated by Car Contract AI • {datetime.datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}")
    elements.append(Paragraph(subtitle_text, SMALL))
    elements.append(Spacer(1, 0.12*inch))

    # Horizontal rule
    elements.append(Spacer(1, 0.08*inch))

    # Summary section
    elements.append(Paragraph("Contract Summary", HEADING_STYLE))
    plain = summary.get("plain_summary", "No summary available.")
    elements.append(Paragraph(plain, NORMAL))
    elements.append(Spacer(1, 0.12*inch))

    # Key numbers
    elements.append(Paragraph("Key Numbers", HEADING_STYLE))
    key_numbers = summary.get("key_numbers", {}) or {}
    if key_numbers:
        kn_rows = [["Field", "Value"]]
        for k, v in key_numbers.items():
            kn_rows.append([str(k), _safe_to_text(v)])
        kn_table = Table(kn_rows, colWidths=[2.7*inch, 2.7*inch])
        kn_table.setStyle(TableStyle([
            ("BACKGROUND", (0,0), (-1,0), colors.HexColor("#34495E")),
            ("TEXTCOLOR", (0,0), (-1,0), colors.white),
            ("GRID", (0,0), (-1,-1), 0.25, colors.grey),
            ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
            ("ALIGN", (0,0), (-1,-1), "LEFT"),
        ]))
        elements.append(kn_table)
    else:
        elements.append(Paragraph("No numeric fields detected.", SMALL))
    elements.append(Spacer(1, 0.12*inch))

    # Red Flags
    elements.append(Paragraph("Red Flags", HEADING_STYLE))
    rf = summary.get("red_flags", []) or []
    if rf:
        # styled box
        rf_text = "<br/>".join([f"• {r}" for r in rf])
        elements.append(Paragraph(rf_text, NORMAL))
    else:
        elements.append(Paragraph("No major red flags detected.", NORMAL))
    elements.append(Spacer(1, 0.12*inch))

    # Fairness score (visual)
    elements.append(Paragraph("Fairness Score", HEADING_STYLE))
    score = summary.get("risk_score", summary.get("fairness_score", None))
    # accept numeric strings
    try:
        score_val = int(score) if score is not None else 0
    except:
        try:
            score_val = int(float(score))
        except:
            score_val = 0
    elements.append(ScoreBar(score_val))
    elements.append(Spacer(1, 0.18*inch))

    # Offer comparison table
    elements.append(Paragraph("Offer Comparison", HEADING_STYLE))
    offer_a = compare.get("offer_a", {}) or {}
    offer_b = compare.get("offer_b", {}) or {}

    fieldsA = offer_a.get("fields", offer_a.get("data", {})) or {}
    fieldsB = offer_b.get("fields", offer_b.get("data", {})) or {}

    all_fields = sorted(set(list(fieldsA.keys()) + list(fieldsB.keys())))
    if not all_fields:
        elements.append(Paragraph("No offer fields available for comparison.", SMALL))
    else:
        table_data = [["Field", "Offer A", "Offer B"]]
        for f in all_fields:
            table_data.append([str(f), _safe_to_text(fieldsA.get(f, "—")), _safe_to_text(fieldsB.get(f, "—"))])

        comp_table = Table(table_data, colWidths=[2.4*inch, 2.1*inch, 2.1*inch])
        comp_table.setStyle(TableStyle([
            ("BACKGROUND", (0,0), (-1,0), colors.HexColor("#2C3E50")),
            ("TEXTCOLOR", (0,0), (-1,0), colors.white),
            ("GRID", (0,0), (-1,-1), 0.25, colors.grey),
            ("ALIGN", (1,1), (-1,-1), "CENTER"),
            ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
        ]))
        elements.append(comp_table)

    elements.append(Spacer(1, 0.18*inch))

    # Scores summary
    elements.append(Paragraph("Offer Scores", HEADING_STYLE))
    sa = offer_a.get("score", "N/A")
    sb = offer_b.get("score", "N/A")
    score_table = Table([["Offer", "Fairness Score"], ["Offer A", str(sa)], ["Offer B", str(sb)]], colWidths=[3*inch, 3*inch])
    score_table.setStyle(TableStyle([
        ("GRID", (0,0), (-1,-1), 0.25, colors.grey),
        ("BACKGROUND", (0,0), (-1,0), colors.HexColor("#1ABC9C")),
        ("TEXTCOLOR", (0,0), (-1,0), colors.white),
        ("ALIGN", (0,0), (-1,-1), "CENTER"),
        ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
    ]))
    elements.append(score_table)
    elements.append(Spacer(1, 0.12*inch))

    best = compare.get("best_offer") or compare.get("best", "A")
    elements.append(Paragraph(f"Recommended Offer: <b>Offer {best}</b>", HEADING_STYLE))
    elements.append(Spacer(1, 0.18*inch))

    # Negotiation Tips (short)
    elements.append(Paragraph("Negotiation Tips (Summary)", HEADING_STYLE))
    neg = compare.get("negotiation_tips", {}) or {}
    polite = neg.get("polite", neg.get("polite_message", "—"))
    firm = neg.get("firm", neg.get("firm_message", "—"))
    legal = neg.get("legal_based", neg.get("legal_message", "—"))

    elements.append(Paragraph("<b>Polite</b>", NORMAL))
    elements.append(Paragraph(polite, NORMAL))
    elements.append(Spacer(1, 0.06*inch))

    elements.append(Paragraph("<b>Firm</b>", NORMAL))
    elements.append(Paragraph(firm, NORMAL))
    elements.append(Spacer(1, 0.06*inch))

    elements.append(Paragraph("<b>Legal-based</b>", NORMAL))
    elements.append(Paragraph(legal, NORMAL))
    elements.append(Spacer(1, 0.18*inch))

    # Full negotiation email templates (copy/paste) in a code-like box
    elements.append(Paragraph("Negotiation Email Templates (copy / paste)", HEADING_STYLE))
    # Build a neat table with three templates
    templates = [
        ("Polite", polite),
        ("Firm", firm),
        ("Legal-Based", legal)
    ]
    for label, text in templates:
        elements.append(Paragraph(f"<b>{label}</b>", NORMAL))
        # render as monospace-like block - using CODE style
        elements.append(Paragraph(text.replace("\n", "<br/>"), CODE))
        elements.append(Spacer(1, 0.08*inch))

    # Footer: confidence and generation timestamp
    elements.append(Spacer(1, 0.16*inch))
    conf = summary.get("confidence", "unknown")
    elements.append(Paragraph(f"Model Confidence: {conf}", SMALL))
    gen_ts = datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    elements.append(Paragraph(f"Generated on: {gen_ts}", SMALL))

    # Build PDF
    doc.build(elements)
    pdf = buffer.getvalue()
    buffer.close()
    return pdf

def build_negotiation_pdf(summary: dict, score: int, reasons: list, negotiation: dict, structured: dict) -> bytes:
    """
    Final unified negotiation PDF generator.
    Compatible with Streamlit + FastAPI + Negotiation Engine.
    """

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter,
                            leftMargin=0.6*inch, rightMargin=0.6*inch,
                            topMargin=0.6*inch, bottomMargin=0.6*inch)

    elements = []

    # Title
    elements.append(Paragraph("Negotiation Pack", TITLE_STYLE))
    elements.append(Paragraph(
        f"Generated by Car Contract AI • {datetime.datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}", SMALL))
    elements.append(Spacer(1, 0.14*inch))

    # Summary
    elements.append(Paragraph("Plain Summary", HEADING_STYLE))
    elements.append(Paragraph(summary.get("plain_summary", "No summary available."), NORMAL))
    elements.append(Spacer(1, 0.14*inch))

    # Fairness Score
    elements.append(Paragraph("Fairness Score", HEADING_STYLE))
    elements.append(ScoreBar(score))
    elements.append(Spacer(1, 0.1*inch))

    # Score Reasons
    elements.append(Paragraph("Why The Score Was Reduced", HEADING_STYLE))
    if reasons:
        for r in reasons:
            elements.append(Paragraph(f"• {r}", NORMAL))
    else:
        elements.append(Paragraph("No reasons detected.", NORMAL))
    elements.append(Spacer(1, 0.14*inch))

    # Negotiation Messages
    elements.append(Paragraph("Negotiation Templates", HEADING_STYLE))

    polite = negotiation.get("polite", "—")
    firm = negotiation.get("firm", "—")
    legal = negotiation.get("legal_based", "—")

    sections = [
        ("Polite — Subject: Request to Review Lease Terms", polite),
        ("Firm — Subject: Term Revision Request", firm),
        ("Legal-Based — Subject: Formal Review of Contract Terms", legal)
    ]

    for title, text in sections:
        elements.append(Paragraph(f"<b>{title}</b>", NORMAL))
        elements.append(Paragraph(text.replace("\n", "<br/>"), CODE))
        elements.append(Spacer(1, 0.12*inch))

    # Structured fields
    elements.append(Paragraph("Key Contract Fields", HEADING_STYLE))
    if structured:
        rows = [["Field", "Value"]]
        for k, v in structured.items():
            rows.append([str(k), _safe_to_text(v)])

        t = Table(rows, colWidths=[2.7*inch, 2.7*inch])
        t.setStyle(TableStyle([
            ("GRID", (0,0), (-1,-1), 0.3, colors.grey),
            ("BACKGROUND", (0,0), (-1,0), colors.HexColor("#34495E")),
            ("TEXTCOLOR", (0,0), (-1,0), colors.white),
            ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
        ]))
        elements.append(t)
    else:
        elements.append(Paragraph("No structured fields detected.", NORMAL))

    elements.append(Spacer(1, 0.14*inch))
    elements.append(Paragraph("This negotiation pack is auto-generated to help users negotiate with dealerships. Not legal advice.", SMALL))

    doc.build(elements)
    pdf = buffer.getvalue()
    buffer.close()
    return pdf

# ============================================================
# PUBLIC ENTRY POINT (USED BY STREAMLIT APP)
# ============================================================

def generate_pdf_report(payload: dict) -> bytes:
    """
    Public PDF generation entry point for Streamlit.
    Returns raw PDF bytes.
    """

    try:
        # 🔁 CHANGE THIS LINE if your internal function name differs
        pdf_bytes = create_pdf(payload)

        # Ensure bytes are returned
        if isinstance(pdf_bytes, bytes):
            return pdf_bytes

        # If file-like object
        if hasattr(pdf_bytes, "read"):
            return pdf_bytes.read()

        raise ValueError("PDF generator did not return bytes")

    except Exception as e:
        raise RuntimeError(f"PDF generation failed: {str(e)}")
