FROM python:3.11-slim
WORKDIR /app
COPY ./app/requirements.txt /app/requirements.txt
RUN apt-get update && apt-get install -y tesseract-ocr poppler-utils libgl1 && rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir -r /app/requirements.txt
COPY ./app /app
ENV PYTHONPATH=/app
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
